[package]
name = "arch-audit"
version = "0.1.11"
authors = ["Andrea Scarpino <me@andreascarpino.it>"]
description = "An utility like pkg-audit for Arch Linux based on Arch Security Team data"
repository = "https://gitlab.com/ilpianista/arch-audit"
license = "MIT"
readme = "README.md"
keywords = ["archlinux", "security"]

[[bin]]
name = "arch-audit"

[dependencies]
alpm = "^0.8"
clap = {version = "^2", features = ["yaml"]}
curl = "^0.4"
env_logger = "^0.7"
itertools = "^0.8"
log = "^0.4"
serde_json = "^1.0"
term = "^0.6"
